version: '3.8'

services:
  nginx-webserver:
    container_name: nginx-webserver
    build: ./nginx_webserver
    ports:
      - "80:80"
    networks:
      - webnet

  tomcat-webserver:
    container_name: tomcat-webserver
    build: ./tomcat_webserver
    ports:
      - "8080:8080"
    networks:
      - webnet

networks:
  webnet:
